### ISSUE TITLE
Little mistake in sample_size.py - MSS(AUC)

### ISSUE THREAD

**Issue by danicastroaraujo** [AndreaCampagner/qualiMLpy#1]
According to the paper (https://www.sciencedirect.com/science/article/pii/S016926072100362X#bib0008), MMS(AUC) should be: 

def mss_auc(auc, prop, target_se = 0.0255):
  for n in range(10, 1000000):
    se = np.sqrt(auc*(1-auc)*(1 + (n/2 - 1)*(1 - auc)/(2- auc) + (n/2 -1)/(1+auc))/(n**2*prop*(1-prop)))
    if se <= target_se:
      return n

and not:
def mss_auc(auc, prop, target_se = 0.0255):
  for n in range(10, 1000000):
    se = np.sqrt(auc*(1-auc)*(1 + (n/2 - 1)*(1 - auc)/(2- auc) + (n/2 -1)*auc/(1+auc))/(n**2*prop*(1-prop)))
    if se <= target_se:
      return n
(there was a multiplication by auc in the last therm of the numerator.)

**Comment by AndreaCampagner** [comment]
Thanks for opening the issue and sorry for the late answer.
The mistake should now be corrected in the code.
